# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WWCxfv1Wyk-_amP3zGqdS_QhVVnpTTX4

# Despliegue

- Cargamos el modelo
- Cargamos los datos futuros
- Aplicar tubería
"""

#Cargamos librerías principales
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

#Paso 1: Limpiar atípicos
def remove_outliers(X):
    #Se asigna valor nulo a los atípicos
    X.loc[(X["Edad"] < 12) | (X["Edad"] > 50), "Edad"] = np.nan
    X.loc[(X["Sexo"] != "Mujer") & (X["Sexo"] != "Hombre"), "Sexo"] = np.nan
    return X

#Cargamos el pipeline con el modelo
import pickle
filename = 'pipeline_modelo.pkl'
pipeline = pickle.load(open(filename, 'rb'))
#pipeline esto mostrara la tuberia

# #Cargamos los datos futuros
# data = pd.read_csv("videojuegos-datosFuturos.csv")
# data.head()

"""#**Stream lit**"""

!pip install streamlit

#Streamlit

#Se crea interfaz gráfica con streamlit para captura de los datos

import streamlit as st

st.title('Predicción de inversión en una tienda de videojuegos')

Edad = st.slider('Edad', min_value=14, max_value=52, value=20, step=1)
videojuego = st.selectbox('Videojuego', ["'Mass Effect'","'Battlefield'", "'Fifa'","'KOA: Reckoning'","'Crysis'","'Sim City'","'Dead Space'","'F1'"])
Plataforma = st.selectbox('Plataforma', ["'Play Station'", "'Xbox'","PC","Otros"])
Sexo = st.selectbox('Sexo', ['Hombre', 'Mujer'])
Consumidor_habitual = st.selectbox('Consumidor_habitual', ['True', 'False'])


#Dataframe
datos = [[Edad, videojuego,Plataforma,Sexo,Consumidor_habitual]]
data = pd.DataFrame(datos, columns=['Edad', 'videojuego','Plataforma','Sexo','Consumidor_habitual']) #Dataframe con los mismos nombres de variable

#Hacemos la predicción con el Tree
Y_Tree = pipeline.predict(data)
print(Y_Tree)

data['Prediccion']=Y_Tree
data